on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
name: Run
jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Build
      run: make build
    - name: Create assets
      run: make release
    - name: Upload binaries
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: aws-usersync-binaries
        path: bin
  publish:
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    name: Publish assets
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve saved aws-usersync binaries
        uses: actions/download-artifact@v2
        with:
          name: aws-usersync-binaries
          path: bin
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}